[tool.poetry]
name = "django-api-forms"
version = "1.0.0-rc.3"
description = "Declarative Django request validation"
authors = [
    "Jakub Dubec <jakub.dubec@gmail.com>",
    "Paul Brown <paul90brown+github@gmail.com>",
    "Erik Bel√°k <erik.belak@backbone.sk>"
]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
Django = ">=2.0"
Pillow = ">=2.1"
msgpack = "*"

[tool.poetry.dev-dependencies]
setuptools = "*"
wheel = "^0.37.1"
twine = "^4.0"
flake8 = "^4.0"
mkdocs-material = "^8.2"
toml = "^0.10.2"
coverage = {version = "^6.4", extras = ["toml"]}

[tool.coverage.run]
omit = [
    '*/tests/*', 'docs/', 'venv/*', 'build/', 'dist/', '.github/', 'django_api_forms.egg-info/', 'setup.py',
    'runtests.py'
]

[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"
