[tool.poetry]
name = "django-api-forms"
version = "0.16.2"
description = "Declarative Django request validation"
authors = ["Jakub Dubec <jakub.dubec@gmail.com>", "Paul Brown <paul90brown+github@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
Django = ">=2.0"
mkdocs-material = "^5.2.3"
Pillow = ">=2.1"
msgpack = "*"
django-enum-choices = "^2.1.2"

[tool.poetry.dev-dependencies]
setuptools = "*"
wheel = "^0.34.2"
twine = "^3.1.1"
flake8 = "^3.7.9"
pytest = "^5.4.1"
pytest-django = "^3.8.0"
pytest-cov = "^2.8.1"
pytest-flake8 = "^1.0.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
